name: Build Slides

on: push

jobs:
  build_slides:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker://pandoc/core:3.1
        with:
          args: >-  # allows you to break string into multiple lines
            -t revealjs -s
            -o index.html README.md
            -V revealjs-url=https://unpkg.com/reveal.js/
            -V theme=solarized
            --include-in-header=slides.css
      - run: mkdir gh-pages && mv index.html gh-pages/
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          keep_files: true
